#!/bin/sh
#
# @name lc_62
#
# @type Standard VTOL
#

. ${R}etc/init.d/rc.vtol_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=lc_62}

param set-default SIM_GZ_EN 1

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 0
param set-default SENS_EN_MAGSIM 1
param set-default SENS_EN_ARSPDSIM 1

param set-default FD_ACT_EN 0
param set-default FD_ACT_MOT_TOUT 500

param set-default CA_METHOD 1
param set-default CA_AIRFRAME 2

param set-default CA_ROTOR_COUNT 8
param set-default CA_ROTOR0_PX 0.0000
param set-default CA_ROTOR0_PY 0.7500
param set-default CA_ROTOR0_KM -0.0500
param set-default CA_ROTOR1_PX 0.0000
param set-default CA_ROTOR1_PY -0.7500
param set-default CA_ROTOR1_KM 0.05
param set-default CA_ROTOR2_PX 1.0300
param set-default CA_ROTOR2_PY -0.7500
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -1.0300
param set-default CA_ROTOR3_PY 0.7500
param set-default CA_ROTOR3_KM 0.0500
param set-default CA_ROTOR4_AX 0.0000
param set-default CA_ROTOR4_AZ -1.0000
param set-default CA_ROTOR4_PX 1.0300
param set-default CA_ROTOR4_PY 0.7500
param set-default CA_ROTOR5_KM -0.0500
param set-default CA_ROTOR5_PX -1.0300
param set-default CA_ROTOR5_PY -0.7500
param set-default CA_ROTOR6_AX 1.0000
param set-default CA_ROTOR6_AZ 0.0000
param set-default CA_ROTOR6_PX -0.4900
param set-default CA_ROTOR6_PY -1.1400
param set-default CA_ROTOR7_AX 1.0000
param set-default CA_ROTOR7_AZ 0.0000
param set-default CA_ROTOR7_KM -0.0500
param set-default CA_ROTOR7_PX -0.4900
param set-default CA_ROTOR7_PY 1.1400

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_MIN1 10
param set-default SIM_GZ_EC_MAX1 2000
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_MIN2 10
param set-default SIM_GZ_EC_MAX2 2000
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_MIN3 10
param set-default SIM_GZ_EC_MAX3 2000
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_MIN4 10
param set-default SIM_GZ_EC_MAX4 2000
param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_MIN5 10
param set-default SIM_GZ_EC_MAX5 2000
param set-default SIM_GZ_EC_FUNC6 106
param set-default SIM_GZ_EC_MIN6 10
param set-default SIM_GZ_EC_MAX6 2000

param set-default SIM_GZ_EC_FUNC7 107
param set-default SIM_GZ_EC_MIN7 0
param set-default SIM_GZ_EC_MAX7 2000
param set-default SIM_GZ_EC_FUNC8 108
param set-default SIM_GZ_EC_MIN8 0
param set-default SIM_GZ_EC_MAX8 2000

param set-default CA_SV_CS_COUNT 5
param set-default CA_SV_CS0_TYPE 1
param set-default CA_SV_CS0_TRQ_R -0.5
param set-default CA_SV_CS1_TYPE 2
param set-default CA_SV_CS1_TRQ_R 0.5
param set-default CA_SV_CS2_TYPE 3
param set-default CA_SV_CS2_TRQ_P 1.0
param set-default CA_SV_CS3_TYPE 3
param set-default CA_SV_CS3_TRQ_P 1.0
param set-default CA_SV_CS4_TYPE 4
param set-default CA_SV_CS4_TRQ_Y 1.0

param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202
param set-default SIM_GZ_SV_FUNC3 203
param set-default SIM_GZ_SV_FUNC4 204
param set-default SIM_GZ_SV_FUNC5 205

param set-default NPFG_PERIOD 12

param set-default FW_PR_FF 0.5000
param set-default FW_PR_P 0.2000
param set-default FW_PSP_OFF 3.0000
param set-default FW_P_LIM_MIN -10.0000
param set-default FW_RR_FF 0.5000
param set-default FW_RR_P 0.2000
param set-default FW_THR_TRIM 0.7500
param set-default FW_THR_MAX 1.0000
param set-default FW_THR_MIN 0.0500
param set-default FW_T_CLMB_MAX 5.0000
param set-default FW_T_SINK_MAX 5.0000
param set-default FW_T_SINK_MIN 2.0000

param set-default MC_AIRMODE 1
param set-default MC_ROLLRATE_P 0.2500
param set-default MC_YAW_P 1.6

param set-default MIS_TAKEOFF_ALT 10
param set-default MPC_XY_P 0.9500
param set-default MPC_XY_VEL_P_ACC 1.0000
param set-default MPC_XY_VEL_I_ACC 0.2000
param set-default MPC_XY_VEL_D_ACC 0.4000
param set-default NAV_ACC_RAD 50.0000
param set-default VT_FWD_THRUST_EN 4
param set-default VT_F_TRANS_THR 1.0000
param set-default VT_TYPE 2

param set-default COM_RCL_EXCEPT 4

param set-default FW_AIRSPD_MAX 40.0000
param set-default FW_AIRSPD_TRIM 25.0000
param set-default FW_MAN_P_MAX 15.0000
param set-default FW_MAN_R_MAX 30.0000
param set-default FW_P_LIM_MAX 15.0000
param set-default FW_P_RMAX_NEG 30.0000
param set-default FW_P_RMAX_POS 30.0000
param set-default FW_P_TC 0.2000
param set-default FW_RLL_TO_YAW_FF 0.1000
param set-default FW_R_LIM 30.0000
param set-default FW_R_RMAX 50.0000
param set-default FW_THR_IDLE 0.1000
param set-default FW_THR_SLEW_MAX 0.6000
param set-default FW_T_HRATE_FF 0.3000
param set-default FW_T_PTCH_DAMP 0.0000
param set-default FW_T_THR_DAMP 0.5000
param set-default FW_WR_IMAX 1.0000
param set-default FW_YR_P 0.1500

param set-default IMU_DGYRO_CUTOFF 30.0000

param set-default MC_PITCHRATE_D 0.0080
param set-default MC_PITCHRATE_I 0.0500
param set-default MC_PITCHRATE_MAX 40.0000
param set-default MC_PITCHRATE_P 0.2500
param set-default MC_PITCH_P 4.0000
param set-default MC_ROLLRATE_D 0.0060
param set-default MC_ROLLRATE_I 0.0500
param set-default MC_ROLLRATE_MAX 70.0000
param set-default MC_ROLL_P 3.0000
param set-default MC_YAWRATE_D 0.0080
param set-default MC_YAWRATE_I 0.0000
param set-default MC_YAWRATE_MAX 25.0000
param set-default MC_YAWRATE_P 1.5000

param set-default MIS_DIST_1WP 10000.0000

param set-default MPC_LAND_SPEED 1.0000
param set-default MPC_MAN_Y_MAX 20.0000
param set-default MPC_THR_HOVER 0.5500
param set-default MPC_TKO_SPEED 1.0000
param set-default MPC_VEL_MANUAL 3.0000
param set-default MPC_XY_CRUISE 3.0000
param set-default MPC_XY_VEL_MAX 5.0000
param set-default MPC_YAWRAUTO_MAX 30.0000
param set-default MPC_YAW_MODE 0
param set-default MPC_Z_VEL_MAX_DN 2.5000

param set-default NAV_DLL_ACT 2
param set-default NAV_LOITER_RAD 400.0000
param set-default NAV_MC_ALT_RAD 0.8000

param set-default RTL_DESCEND_ALT 10.0000

param set-default VT_B_DEC_FF 0.0450
param set-default VT_B_DEC_I 0.0000
param set-default VT_QC_T_ALT_LOSS 60.0000
param set-default VT_TRANS_TIMEOUT 60.0000

param set-default FD_ESCS_EN 0

param set-default UXRCE_DDS_SYNCT 0
