#!/bin/sh
#
# @name lc_62
#
# @type Standard VTOL
#

. ${R}etc/init.d/rc.vtol_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=lc_62}

param set-default SIM_GZ_EN 1

param set-default SENS_EN_ARSPDSIM 1

param set-default FD_ACT_EN 0
param set-default FD_ACT_MOT_TOUT 500

param set-default CA_AIRFRAME 2

param set-default COM_PREARM_MODE 2

param set-default CA_ROTOR_COUNT 8

param set-default CA_ROTOR0_PX 0.0000
param set-default CA_ROTOR0_PY 0.7475
param set-default CA_ROTOR0_KM -0.05

param set-default CA_ROTOR1_PX 0.0000
param set-default CA_ROTOR1_PY -0.7475
param set-default CA_ROTOR1_KM 0.05

param set-default CA_ROTOR2_PX 1.0300
param set-default CA_ROTOR2_PY -0.7475
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -1.0300
param set-default CA_ROTOR3_PY 0.7475
param set-default CA_ROTOR3_KM 0.05

param set-default CA_ROTOR4_PX 1.0300
param set-default CA_ROTOR4_PY 0.7475
param set-default CA_ROTOR4_KM 0.05

param set-default CA_ROTOR5_PX -1.0300
param set-default CA_ROTOR5_PY -0.7475
param set-default CA_ROTOR5_KM -0.05

param set-default CA_ROTOR6_AX 1.0000
param set-default CA_ROTOR6_AY 0
param set-default CA_ROTOR6_AZ 0
param set-default CA_ROTOR6_PX -0.4900
param set-default CA_ROTOR6_PY 0
param set-default CA_ROTOR6_KM 0

param set-default CA_ROTOR7_AX 1
param set-default CA_ROTOR7_AY 0
param set-default CA_ROTOR7_AZ 0
param set-default CA_ROTOR7_PX -0.4900
param set-default CA_ROTOR7_PY 0
param set-default CA_ROTOR7_KM 0

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_MIN1 10
param set-default SIM_GZ_EC_MAX1 1500

param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_MIN2 10
param set-default SIM_GZ_EC_MAX2 1500

param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_MIN3 10
param set-default SIM_GZ_EC_MAX3 1500

param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_MIN4 10
param set-default SIM_GZ_EC_MAX4 1500

param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_MIN5 10
param set-default SIM_GZ_EC_MAX5 1500

param set-default SIM_GZ_EC_FUNC6 106
param set-default SIM_GZ_EC_MIN6 10
param set-default SIM_GZ_EC_MAX6 1500

param set-default SIM_GZ_EC_FUNC7 107
param set-default SIM_GZ_EC_MIN7 0
param set-default SIM_GZ_EC_MAX7 3500

param set-default SIM_GZ_EC_FUNC8 108
param set-default SIM_GZ_EC_MIN8 0
param set-default SIM_GZ_EC_MAX8 3500

param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202
param set-default SIM_GZ_SV_FUNC3 203
param set-default SIM_GZ_SV_FUNC4 204
param set-default SIM_GZ_SV_FUNC5 205

param set-default COM_RC_IN_MODE 1

param set-default CA_SV_CS_COUNT 5

param set-default CA_SV_CS0_TYPE 1
param set-default CA_SV_CS0_TRQ_R -0.5

param set-default CA_SV_CS1_TYPE 2
param set-default CA_SV_CS1_TRQ_R 0.5

param set-default CA_SV_CS2_TYPE 3
param set-default CA_SV_CS2_TRQ_P 1

param set-default CA_SV_CS3_TYPE 3
param set-default CA_SV_CS3_TRQ_P 1

param set-default CA_SV_CS4_TYPE 4
param set-default CA_SV_CS4_TRQ_Y 1

param set-default NPFG_PERIOD 12
param set-default FW_PR_FF 0.2
param set-default FW_PR_P 0.9
param set-default FW_PSP_OFF 2
param set-default FW_P_LIM_MIN -15
param set-default FW_RR_FF 0.1
param set-default FW_RR_P 0.3
param set-default FW_THR_TRIM 0.25
param set-default FW_THR_MAX 0.6
param set-default FW_THR_MIN 0.05
param set-default FW_T_CLMB_MAX 8
param set-default FW_T_SINK_MAX 2.7
param set-default FW_T_SINK_MIN 2.2
param set-default FW_AIRSPD_TRIM 30
param set-default FW_AIRSPD_MAX 40
param set-default FW_AIRSPD_MIN 20

param set-default MC_AIRMODE 1
param set-default MC_ROLLRATE_P 0.3
param set-default MC_YAW_P 1.6

param set-default MIS_TAKEOFF_ALT 10

param set-default MPC_XY_P 0.8
param set-default MPC_XY_VEL_P_ACC 3
param set-default MPC_XY_VEL_I_ACC 4
param set-default MPC_XY_VEL_D_ACC 0.1

param set-default NAV_ACC_RAD 5
param set-default NAV_DLL_ACT 0
param set-default COM_RCL_EXCEPT 31

param set-default VT_F_TRANS_DUR 10
param set-default VT_F_TR_OL_TM 30
param set-default VT_TRANS_TIMEOUT 30
param set-default VT_ARSP_TRANS 30.0
param set-default VT_ARSP_BLEND 25.0
param set-default VT_FWD_THRUST_EN 0
param set-default VT_F_TRANS_THR 1
param set-default VT_TYPE 2
param set-default FD_ESCS_EN 0
